# 实盘信号检测

In [1]:
with open("vt_20181023.log","r",encoding="utf-8") as f:
    content = f.readlines()
data = []
for logRow in content:
    if logRow.find("CTA_STRATEGY	ARPSYMaStrategy:on60MinBar")>=0:
        result = logRow.split("CTA_STRATEGY	ARPSYMaStrategy:on60MinBar")[-1]
        data.append(result)

In [2]:
import pandas as pd
from datetime import datetime

In [3]:
checkDict = {'datetime':[],'score-1':[],'score-2':[],'crossOver':[],'crossBelow':[],'maTrend':[]}
for row in data:
    dateTime = row[row.find('time')+5:29]
    rigthTime = datetime.strptime(dateTime, "%Y-%m-%d %H:%M:%S")
    checkDict['datetime'].append(rigthTime)
    checkDict['score-1'].append(row[row.find('score-1')+8:].split(',')[0])
    checkDict['score-2'].append(row[row.find('score-2')+8:].split(',')[0])
    checkDict['crossOver'].append(row[row.find('crossOver')+10])
    checkDict['crossBelow'].append(row[row.find("crossBelow")+11])
    checkDict['maTrend'].append(row[row.find("maTrend")+8])

In [4]:
realCheck = pd.DataFrame(checkDict)

In [5]:
realCheckDf = realCheck.set_index('datetime')

In [6]:
realCheckDf

                    cross trend wave
datetime
2018-10-23 09:33:00     0     0    0
2018-10-23 09:34:00     0     0    0
2018-10-23 09:35:00     0     0    0
2018-10-23 09:36:00     0     0    0
2018-10-23 09:37:00     0     0    0
2018-10-23 09:38:00     0     0    0
2018-10-23 09:39:00     0     0    0
2018-10-23 09:40:00     0     0    0
2018-10-23 09:41:00     0     0    0
2018-10-23 09:42:00     0     0    0
2018-10-23 09:43:00     0     0    0
2018-10-23 09:44:00     0     0    0
2018-10-23 09:45:00     0     0    0
2018-10-23 09:46:00     0     0    0
2018-10-23 09:47:00     0     0    0
2018-10-23 09:48:00     0     0    0
2018-10-23 09:49:00     0     0    0
2018-10-23 09:50:00     0     0    0
2018-10-23 09:51:00     0     0    0
2018-10-23 09:52:00     0     0    0
2018-10-23 09:53:00     0     0    0
2018-10-23 09:54:00     0     0    0
2018-10-23 09:55:00     0     0    0
2018-10-23 09:56:00     0     0    0
2018-10-23 09:57:00     0     0    0
2018-10-23 09:58:00     0     0    0
2018-10-23 09:59:00     0     0    0
2018-10-23 10:00:00     0     0    0
2018-10-23 10:01:00     0     0    0
2018-10-23 10:02:00     0     0    0
...                   ...   ...  ...
2018-10-24 20:48:00     1     1   -1
2018-10-24 20:49:00     1     1   -1
2018-10-24 20:50:00     1     1   -1
2018-10-24 20:51:00     1     1   -1
2018-10-24 20:52:00     1     1   -1
2018-10-24 20:53:00     1     1   -1
2018-10-24 20:54:00     1     1   -1
2018-10-24 20:55:00     1     1   -1
2018-10-24 20:56:00     1     1   -1
2018-10-24 20:57:00     1     1   -1
2018-10-24 20:58:00     1     1   -1
2018-10-24 20:59:00     1     1   -1
2018-10-24 21:00:00     1     1   -1
2018-10-24 21:01:00     1     1   -1
2018-10-24 21:02:00     1     1   -1
2018-10-24 21:03:00     1     1   -1
2018-10-24 21:04:00     1     1   -1
2018-10-24 21:05:00     1     1   -1
2018-10-24 21:06:00     1     1   -1
2018-10-24 21:07:00     1     1   -1
2018-10-24 21:08:00     1     1   -1
2018-10-24 21:09:00     1     1   -1
2018-10-24 21:10:00     1     1   -1
2018-10-24 21:11:00     1     1   -1
2018-10-24 21:12:00     1     1   -1
2018-10-24 21:13:00     1     1   -1
2018-10-24 21:14:00     1     1   -1
2018-10-24 21:15:00     1     1   -1
2018-10-24 21:16:00     1     1   -1
2018-10-24 21:17:00     1     1   -1

[1959 rows x 3 columns]

# 回测信号检查

In [58]:
checkBtDict = {'datetime':[],'score-1':[],'score-2':[],'crossOver':[],'crossBelow':[],'maTrend':[]}

In [59]:
import pandas as pd

btLog = pd.read_csv('BacktestLog.csv')
btData = []

for i, value in btLog.iterrows():
    if value.values[0].find("ARPSYMaStrategy:on60MinBar")>=0:
        result = value.values[0].split("ARPSYMaStrategy:on60MinBar")[-1]
        btData.append(result)

In [43]:
result

',datetime:2018-12-05 06:00:00,score-1:7,score-2:8,crossOver:False,crossBelow:False,maTrend:1'

In [49]:
result[result.find('maTrend')+8]

'1'

In [60]:
from datetime import datetime

for row in btData:
    dateTime = row[row.find('time')+5:29]
    rigthTime = datetime.strptime(dateTime, "%Y-%m-%d %H:%M:%S")
    checkBtDict['datetime'].append(rigthTime)
    checkBtDict['score-1'].append(row[row.find('score-1')+8:].split(',')[0])
    checkBtDict['score-2'].append(row[row.find('score-2')+8:].split(',')[0])
    checkBtDict['crossOver'].append(row[row.find('crossOver')+10])
    checkBtDict['crossBelow'].append(row[row.find("crossBelow")+11])
    checkBtDict['maTrend'].append(row[row.find("maTrend")+8])

In [61]:
checkBtData = pd.DataFrame(checkBtDict)

In [62]:
checkBtDd = checkBtData.set_index('datetime')

In [63]:
checkBtDd

                    score-1 score-2 crossOver crossBelow maTrend
datetime
2018-01-08 06:00:00       8       7         F          F       0
2018-01-08 07:00:00       9       8         F          F       0
2018-01-08 08:00:00       9       9         F          F       0
2018-01-08 09:00:00       9       9         F          F       0
2018-01-08 10:00:00      10       9         F          F       0
2018-01-08 11:00:00       9      10         F          F       0
2018-01-08 12:00:00       9       9         F          F       0
2018-01-08 13:00:00       8       9         F          F       0
2018-01-08 14:00:00       7       8         F          F       0
2018-01-08 15:00:00       7       7         F          F       0
2018-01-08 16:00:00       6       7         F          F       0
2018-01-08 17:00:00       2       6         F          F       0
2018-01-08 18:00:00       2       2         F          F       0
2018-01-08 19:00:00       3       2         F          F       0
2018-01-08 20:00:00       5       3         F          F       0
2018-01-08 21:00:00       3       5         F          F       0
2018-01-08 22:00:00       2       3         F          F       0
2018-01-08 23:00:00       2       2         F          F       0
2018-01-09 00:00:00       7       2         F          F       0
2018-01-09 01:00:00       9       7         F          F       0
2018-01-09 02:00:00      12       9         F          F       0
2018-01-09 03:00:00      14      12         F          F       0
2018-01-09 04:00:00      13      14         F          F       0
2018-01-09 05:00:00      14      13         F          F       0
2018-01-09 06:00:00      14      14         F          F       0
2018-01-09 07:00:00      16      14         F          F       0
2018-01-09 08:00:00      16      16         F          F       0
2018-01-09 09:00:00      16      16         F          F       0
2018-01-09 10:00:00      15      16         F          F       0
2018-01-09 11:00:00      10      15         F          F       0
...                     ...     ...       ...        ...     ...
2018-12-04 01:00:00       2       0         F          F       -
2018-12-04 02:00:00       2       2         F          F       -
2018-12-04 03:00:00       4       2         F          F       -
2018-12-04 04:00:00       6       4         F          F       -
2018-12-04 05:00:00       8       6         F          F       -
2018-12-04 06:00:00       9       8         F          F       -
2018-12-04 07:00:00      13       9         T          F       -
2018-12-04 08:00:00      14      13         F          F       -
2018-12-04 09:00:00      13      14         F          F       -
2018-12-04 10:00:00      13      13         F          F       -
2018-12-04 11:00:00      12      13         F          F       -
2018-12-04 12:00:00       9      12         F          F       -
2018-12-04 13:00:00       8       9         F          F       -
2018-12-04 14:00:00       9       8         F          F       -
2018-12-04 15:00:00      11       9         F          F       -
2018-12-04 16:00:00      10      11         F          F       -
2018-12-04 17:00:00      10      10         F          F       -
2018-12-04 18:00:00      10      10         F          F       -
2018-12-04 19:00:00      12      10         F          F       -
2018-12-04 20:00:00      11      12         F          F       -
2018-12-04 21:00:00      14      11         T          F       -
2018-12-04 22:00:00      17      14         F          F       -
2018-12-04 23:00:00      18      17         F          F       -
2018-12-05 00:00:00      18      18         F          F       1
2018-12-05 01:00:00      15      18         F          F       1
2018-12-05 02:00:00      15      15         F          F       1
2018-12-05 03:00:00      14      15         F          F       1
2018-12-05 04:00:00      12      14         F          F       1
2018-12-05 05:00:00       8      12         F          F       1
2018-12-05 06:00:00       7       8         F          F       1

[7881 rows x 5 columns]

In [12]:
FinalDf = pd.concat([checkBtDd, realCheckDf], axis=1).dropna()

In [13]:
FinalDf

                     close cross trend wave    n cross trend wave
datetime
2018-10-23 09:33:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:34:00  5.441   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:35:00  5.440   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:36:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:37:00  5.437   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:38:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:39:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:40:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:41:00  5.435   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:42:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:43:00  5.431   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:44:00  5.433   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:45:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:46:00  5.434   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:47:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:48:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:49:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:50:00  5.438   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:51:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:52:00  5.437   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:53:00  5.430   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:54:00  5.434   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:55:00  5.433   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:56:00  5.433   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:57:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:58:00  5.431   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:59:00  5.431   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 10:00:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 10:01:00  5.435   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 10:02:00  5.437   1.0   1.0 -1.0  0.0     0     0    0
...                    ...   ...   ...  ...  ...   ...   ...  ...
2018-10-24 07:30:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:31:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:32:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:33:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:34:00  5.416   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:35:00  5.416   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:36:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:37:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:38:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:39:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:40:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:41:00  5.412   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:42:00  5.413   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:43:00  5.413   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:44:00  5.412   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:45:00  5.411   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:46:00  5.412   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:47:00  5.407   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:48:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:49:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:50:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:51:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:52:00  5.408   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:53:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:54:00  5.408   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:55:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:56:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:57:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:58:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:59:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1

[1161 rows x 8 columns]

In [14]:
FinalDf.to_excel('CheckSignal.xlsx')