# 实盘信号检测

In [1]:
with open("vt_20181023.log","r",encoding="utf-8") as f:
    content = f.readlines()
data = []
for logRow in content:
    if logRow.find("CTA_STRATEGY	ARPSYMaStrategy:on60MinBar")>=0:
        result = logRow.split("CTA_STRATEGY	ARPSYMaStrategy:on60MinBar")[-1]
        data.append(result)

In [2]:
import pandas as pd
from datetime import datetime

In [3]:
checkDict = {'datetime':[],'score-1':[],'score-2':[],'crossOver':[],'crossBelow':[],'maTrend':[]}
for row in data:
    dateTime = row[row.find('time')+5:29]
    rigthTime = datetime.strptime(dateTime, "%Y-%m-%d %H:%M:%S")
    checkDict['datetime'].append(rigthTime)
    checkDict['score-1'].append(row[row.find('score-1')+8:].split(',')[0])
    checkDict['score-2'].append(row[row.find('score-2')+8:].split(',')[0])
    checkDict['crossOver'].append(row[row.find('crossOver')+10])
    checkDict['crossBelow'].append(row[row.find("crossBelow")+11])
    checkDict['maTrend'].append(row[row.find("maTrend")+8])

In [4]:
realCheck = pd.DataFrame(checkDict)

In [5]:
realCheckDf = realCheck.set_index('datetime')

In [6]:
realCheckDf

                    cross trend wave
datetime
2018-10-23 09:33:00     0     0    0
2018-10-23 09:34:00     0     0    0
2018-10-23 09:35:00     0     0    0
2018-10-23 09:36:00     0     0    0
2018-10-23 09:37:00     0     0    0
2018-10-23 09:38:00     0     0    0
2018-10-23 09:39:00     0     0    0
2018-10-23 09:40:00     0     0    0
2018-10-23 09:41:00     0     0    0
2018-10-23 09:42:00     0     0    0
2018-10-23 09:43:00     0     0    0
2018-10-23 09:44:00     0     0    0
2018-10-23 09:45:00     0     0    0
2018-10-23 09:46:00     0     0    0
2018-10-23 09:47:00     0     0    0
2018-10-23 09:48:00     0     0    0
2018-10-23 09:49:00     0     0    0
2018-10-23 09:50:00     0     0    0
2018-10-23 09:51:00     0     0    0
2018-10-23 09:52:00     0     0    0
2018-10-23 09:53:00     0     0    0
2018-10-23 09:54:00     0     0    0
2018-10-23 09:55:00     0     0    0
2018-10-23 09:56:00     0     0    0
2018-10-23 09:57:00     0     0    0
2018-10-23 09:58:00     0     0    0
2018-10-23 09:59:00     0     0    0
2018-10-23 10:00:00     0     0    0
2018-10-23 10:01:00     0     0    0
2018-10-23 10:02:00     0     0    0
...                   ...   ...  ...
2018-10-24 20:48:00     1     1   -1
2018-10-24 20:49:00     1     1   -1
2018-10-24 20:50:00     1     1   -1
2018-10-24 20:51:00     1     1   -1
2018-10-24 20:52:00     1     1   -1
2018-10-24 20:53:00     1     1   -1
2018-10-24 20:54:00     1     1   -1
2018-10-24 20:55:00     1     1   -1
2018-10-24 20:56:00     1     1   -1
2018-10-24 20:57:00     1     1   -1
2018-10-24 20:58:00     1     1   -1
2018-10-24 20:59:00     1     1   -1
2018-10-24 21:00:00     1     1   -1
2018-10-24 21:01:00     1     1   -1
2018-10-24 21:02:00     1     1   -1
2018-10-24 21:03:00     1     1   -1
2018-10-24 21:04:00     1     1   -1
2018-10-24 21:05:00     1     1   -1
2018-10-24 21:06:00     1     1   -1
2018-10-24 21:07:00     1     1   -1
2018-10-24 21:08:00     1     1   -1
2018-10-24 21:09:00     1     1   -1
2018-10-24 21:10:00     1     1   -1
2018-10-24 21:11:00     1     1   -1
2018-10-24 21:12:00     1     1   -1
2018-10-24 21:13:00     1     1   -1
2018-10-24 21:14:00     1     1   -1
2018-10-24 21:15:00     1     1   -1
2018-10-24 21:16:00     1     1   -1
2018-10-24 21:17:00     1     1   -1

[1959 rows x 3 columns]

# 回测信号检查

In [21]:
checkBtDict = {'datetime':[],'CurSignal':[],'maTrend':[],'CurvolSignal':[],'Stoptracking':[],'maStop':[],'longStop':[],'longProfit':[],'shortStop':[],'shortProfit':[]}

In [22]:
import pandas as pd

btLog = pd.read_csv('BacktestLog.csv')
btData = []

for i, value in btLog.iterrows():
    if value.values[0].find("Overshoot:on1MinBar")>=0:
        result = value.values[0].split("Overshoot:on1MinBar")[-1]
        btData.append(result)

In [2]:
result

',datetime:2018-12-10 07:58:00,CurSignal:0,maTrend:-1,CurvolSignal:0,Stoptracking:0.011642348279934411,maStop:shortstop,longStop:2.5190271469389316,longProfit:2.6970642653053445,shortStop:2.578372853061069,shortProfit:2.400335734694656'

In [23]:
result[result.find('maStop')+7:]

'shortstop,longStop:2.5190271469389316,longProfit:2.6970642653053445,shortStop:2.578372853061069,shortProfit:2.400335734694656'

In [25]:
from datetime import datetime

for row in btData:
    dateTime = row[row.find('time')+5:29]
    rigthTime = datetime.strptime(dateTime, "%Y-%m-%d %H:%M:%S")
    checkBtDict['datetime'].append(rigthTime)
    checkBtDict['CurSignal'].append(row[row.find('CurSignal')+10:].split(',')[0])
    checkBtDict['maTrend'].append(row[row.find('maTrend')+8:].split(',')[0])
    checkBtDict['CurvolSignal'].append(row[row.find('CurvolSignal')+13:].split(',')[0])
    checkBtDict['Stoptracking'].append(row[row.find("Stoptracking")+13:].split(',')[0])
    checkBtDict['maStop'].append(row[row.find("maStop")+7:].split(',')[0])
    checkBtDict['longStop'].append(row[row.find("longStop")+9:].split(',')[0])
    checkBtDict['shortStop'].append(row[row.find("shortStop")+10:].split(',')[0])
    checkBtDict['shortProfit'].append(row[row.find("shortProfit")+12:].split('\'')[0])

In [26]:
checkBtData = pd.DataFrame(checkBtDict)

ValueError: arrays must all be same length

In [18]:
checkBtDd = checkBtData.set_index('datetime')

NameError: name 'checkBtData' is not defined

In [19]:
checkBtDd

NameError: name 'checkBtDd' is not defined

In [12]:
FinalDf = pd.concat([checkBtDd, realCheckDf], axis=1).dropna()

In [13]:
FinalDf

                     close cross trend wave    n cross trend wave
datetime
2018-10-23 09:33:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:34:00  5.441   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:35:00  5.440   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:36:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:37:00  5.437   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:38:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:39:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:40:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:41:00  5.435   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:42:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:43:00  5.431   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:44:00  5.433   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:45:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:46:00  5.434   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:47:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:48:00  5.436   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:49:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:50:00  5.438   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:51:00  5.439   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:52:00  5.437   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:53:00  5.430   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:54:00  5.434   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:55:00  5.433   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:56:00  5.433   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:57:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:58:00  5.431   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 09:59:00  5.431   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 10:00:00  5.432   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 10:01:00  5.435   1.0   1.0 -1.0  0.0     0     0    0
2018-10-23 10:02:00  5.437   1.0   1.0 -1.0  0.0     0     0    0
...                    ...   ...   ...  ...  ...   ...   ...  ...
2018-10-24 07:30:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:31:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:32:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:33:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:34:00  5.416   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:35:00  5.416   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:36:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:37:00  5.415   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:38:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:39:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:40:00  5.414   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:41:00  5.412   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:42:00  5.413   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:43:00  5.413   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:44:00  5.412   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:45:00  5.411   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:46:00  5.412   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:47:00  5.407   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:48:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:49:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:50:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:51:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:52:00  5.408   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:53:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:54:00  5.408   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:55:00  5.409   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:56:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:57:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:58:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1
2018-10-24 07:59:00  5.410   1.0   1.0 -1.0  0.0     1     1   -1

[1161 rows x 8 columns]

In [14]:
FinalDf.to_excel('CheckSignal.xlsx')